CREATE PROCEDURE [dbo].[CheckPersonTimeEntriesAfterTerminationDate]
(
	@PersonId	INT,
	@TerminationDate	DATETIME
)
AS
BEGIN
	DECLARE @TimeEntriesExists BIT

	IF EXISTS(
				SELECT 1 FROM dbo.TimeEntry TE
				WHERE TE.PersonId = @PersonId AND TE.ChargeCodeDate >= @TerminationDate AND TE.IsAutoGenerated <> 1
			)
		SET @TimeEntriesExists  = 1
	ELSE
		SET @TimeEntriesExists = 0

	SELECT @TimeEntriesExists

END
